### ISSUE TITLE
Add your public SSH key inside the `ssh_keys` folder and then add the path to the `general.yaml` file

### ISSUE THREAD

**Issue by lsibi** [remla25-team8/operation#8]
I suggest you to copy the SSH public key with your names. Then add your SSH public keys here inside `general.yaml`:

```yaml
    - name: Add SSH public keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_items:
        - "files/ssh_keys/lorenzo.pub"
        - "files/ssh_keys/<YOUR-NAME>.pub"
```
